### ISSUE TITLE
Class namespacing or weird bug?

### ISSUE THREAD

**Issue by atomless** [jkphl/svg-sprite#110]
It appears that svg-sprite is adding random characters to the start of class names. Is this something I can set a config to prevent or just a bug?

I also reported this issue here as I'm using svg-sprite via gulp https://github.com/jkphl/gulp-svg-sprite/issues/36

**Comment by jkphl** [comment]
Hey @atomless,

that's definitely a feature, not a bug. Please see [here](https://github.com/jkphl/svg-sprite/issues/42). You can configure CSS class namespacing via the appropriate config options — please [read the documentation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#sprite-svg-options) (`namespaceClassnames`).

Cheers, Joschi

**Comment by atomless** [comment]
Aha, okay, but I really don't think a new feature in a widely used lib like this should come along in an update and by defaultbreak all your classes names by adding namespaces that were not an option before so users won't have the required configuration set to avoid them. Better to have things like this default to false IMHO.

**Comment by jkphl** [comment]
I get your point.

However, my experience was that the majority of users doesn't care at all about the internals of their SVG files. They are / were not aware of the CSS class names and don't use them for animations, external styling or whatsoever. In fact, most of the users don't even care if they use CSS styles or presentation attributes — which is part of the problem. I got a lot of "complaints" like [this one](https://github.com/jkphl/svg-sprite/issues/41) where people just didn't understand what was going wrong. The fact that e.g. Illustrator uses the exact same class names for all exported files and that using CSS styles seems to be the default lead to a lot of problematic sprites.

I'm sure that the vast majority of *svg-sprite* users didn't recognize the change at all if not by suddenly having working sprites. Sorry for any inconvenience you may have had caused by this change, but I suppose you were one of the very few in this case.
