### ISSUE TITLE
Blank symbol ids?

### ISSUE THREAD

**Issue by SachaG** [jkphl/svg-sprite#112]
I'm trying to wrap this package for use with Meteor (by parsing SVGs, compiling them into a single sprite, and then injecting the sprite directly into the DOM generated by Meteor), and I've almost got it working: 

https://github.com/SachaG/compile-svg/blob/master/lib/compile-svg.js

The only problem is that the generated `<symbol>`'s `id` attribute is blank. Any idea what could be the reason?

**Comment by jkphl** [comment]
Hi @SachaG,

first of all, I don't have any clue of Meteor, but I hope I can help you anyway. I'll try my best at least.

Given that you provided a [custom ID generator function](https://github.com/SachaG/compile-svg/blob/master/lib/compile-svg.js#L29), what's the output of that `console.log()`?

Furthermore, the default generator function that you are overriding looks something like this:

```js
function (name) {
	return path.basename(name.split(path.sep).join(this.separator).replace(/\s+/g, this.whitespace), '.svg');
}
```

It is called with the full (relative) file path as single argument, strips the file extension, replaces whitespace against underscore (configurable) and the path separator against double dashes (configurable) and returns the result as the ID for the shape. Your replacement function should deal with the same tasks, at least. Right now it looks like your generator function simply returns the file path, which might be a problem in some situations.

Please let me know what your `console.log()` is printing, then we'll see what we can do. 頑張って!

**Comment by SachaG** [comment]
So that console.log doesn't output anything… And this is what I get if I remove that whole `shape` block including the `id` generator function, and pass `null` as a name in `spriter.add()`:

```
2015-09-06 18:20:48 - verbose: Initialized spriter configuration
2015-09-06 18:20:48 - debug: Created processing queue instance
2015-09-06 18:20:48 - info: Created spriter instance
2015-09-06 18:20:48 - debug: Added "" to processing queue
2015-09-06 18:20:48 - verbose: Added shape ":regular"
2015-09-06 18:20:48 - debug: Optimized "" with SVGO (saved 616 Bytes / 62%)
```

I get the exact same log output even if I do pass a name option. It's strange, it's like the name is not getting passed through…

**Comment by SachaG** [comment]
By the way, I would be happy with the default id based on the file name. I only added my own custom generator function to try and work things out.

**Comment by jkphl** [comment]
I'm on the road right now, but I will try to reproduce this as soon as possible. Will get back to you.

**Comment by jkphl** [comment]
Hey @SachaG,

I tried to look into your issue now, but unfortunately I'm not able to reproduce it. Everything just works fine on my side, but as I said before I can't test in the context of Meteor (as I have no clue of it). There's one little detail I noticed, however: There's no `"inline"` config option as you use it. Instead you will want to use something like this:

```javascript
{
    "mode": {
        "symbol": {
            "inline": true
        }
    }
}
```

This won't fix your problem though, it's just one thing I spotted in your example. To quickly get a grab on the config, you might always use the [online configurator / kickstarter](http://jkphl.github.io/svg-sprite) by the way.

The line where things go wrong is probably this one:

>     2015-09-06 18:20:48 - debug: Added "" to processing queue

This line is emitted [here](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/queue.js#L50), and the method is called [here](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite.js#L126). It looks like it's not a proper vinyl file that is getting passed around. In your case, the vinyl file is created [here](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite.js#L126) — so maybe you should try to debug the `file` variable somewhere between these lines?! What happens if you insert `console.log(file)` at [line 122](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite.js#L122) and then once more at [line 124](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite.js#L124)?

**Comment by SachaG** [comment]
Thanks for the tips! I'll keep digging… And I'd love to try logging out at these lines, but to be honest I'm not sure how to run an NPM package from a local copy when it's being used by a Meteor app… This is an intersection of Meteor and Node that I haven't had to deal with yet!

**Comment by jkphl** [comment]
Good luck! If there's anything I can help you with just let me know. :)

**Comment by SachaG** [comment]
So `console.log` on those two lines gives me the same thing twice:

```
<File "animation.svg" <Buffer 3c 73 76 67 20 76 65 72 73 69 6f 6e 3d 22 31 2e 31 22 20 69 64 3d 22 4c 61 79 65 72 5f 31 22 20 78 6d 6c 6e 73 3d 22 68 74 74 70 3a 2f 2f 77 77 77 2e 77 ...>>
```

Is this what it should look like?

**Comment by SachaG** [comment]
OK so I've identified the issue. 

- `file.path` gives me `svg/animation.svg`
- `file.base` gives me `/Users/sacha/Dev/screenings/svg`
- `file.base.length` gives me `31`
- `path.sep` gives me `/`
- `file.path.substr(file.base.length + path.sep.length)` gives me `""`. 

I'm guessing `file.path` should not be shorter than `file.base`?

**Comment by jkphl** [comment]
That's it! `file.path` should be the **full absolute path** of the sprite, not the relative path to your `cwd`. I couldn't see this from your source and thought that the variable `fullPath` is just that -- the full path. ;)
Try to change this and make it absolute, and everything should work! :)

**Comment by SachaG** [comment]
Yay, finally fixed it! Thanks so much for your help!

**Comment by jkphl** [comment]
You're very welcome! Happy spriting! :)
