### ISSUE TITLE
Why is phantomjs a dependency?

### ISSUE THREAD

**Issue by axe312ger** [jkphl/svg-sprite#113]
Hello there,

we got problems in our build process since phantomjs can not be build. We figured out that your module is requiring phantomjs.

So now I am wondering why you need it? And why is it a dependency and not a dev dependency?

Thank you,
Benedikt

**Comment by jkphl** [comment]
Hi @axe312ger,

PhantomJS is needed for determining the actual size of an SVG shape in case there are no dimension properties given in the SVG file. You're right, having PhantomJS as a hardwired dependency is somewhat unpleasant — I don't know of a way to make it optional / configurable though. I'm open for suggestions (making it a dev dependency is not a solution, however).

Cheers, Joschi

**Comment by jkphl** [comment]
Btw. what platform are you on? Requiring PhantomJS normally shouldn't be a problem ...

**Comment by axe312ger** [comment]
Wow fast reaction. Thx.
We are on https://platform.sh/, the build seems to fail from time to time. Maybe my colleague can give more infos, i'll inform him.

**Comment by pixelmord** [comment]
@axe312ger @jkphl Thanks for looking into this, our build process has nothing to do with this, it was just the reason why we noticed that this project has this dependency on phantomjs.
Build process failed because at that specific moment phantomjs could not be installed.

We were only just wondering why this dependency is there at all...
However you answered that, thanks for your quick reaction!

Cheers Andy

**Comment by jkphl** [comment]
@axe312ger @pixelmord No problem, you're very welcome!

As I said, I'm aware of that dependency's heavy duty and I would love to ged rid of it in the sense that I'd love to have it configurable. If you know of any way to achieve this I'd love to hear your suggestions.

Happy spriting! :)
