### ISSUE TITLE
How to set symbol ID ? Online generator seems not work properly for grunt and SVGO

### ISSUE THREAD

**Issue by craft37** [jkphl/svg-sprite#120]
Code below doesn't work.

```
prefix          : "svg-%s",
            
          shape       : {
            id              : {                         
            separator       : '-',                     
            generator       : function() { /*...*/ },   
            pseudo          : '~'                       
         },
```

**Comment by jkphl** [comment]
Where does this configuration come from? It's totally incomplete, the `generator` function seems to have no effect at all (which will completely break the symbol ID). Please post your **complete** configuration and try to validate it with the [online kickstarter](http://jkphl.github.io/svg-sprite) before.

**Comment by craft37** [comment]
Sorry, I use Grunt.

Online-generator seems doesnt work cause not including transformation setted and describes var Gulp in grunt tab. Or maybe it's ok and I not using it properly.
What could be wrong?

![screenshot from 2015-10-19 03-52-52](https://cloud.githubusercontent.com/assets/3589618/10567742/085a5328-7615-11e5-88a0-e7e6924b946c.png)

**Comment by jkphl** [comment]
Oh wow, thanks for the heads up! That was definitely a bug in the online configurator, I just fixed it.

Custom transformations — as well as a custom ID generator function — cannot be part of the online configurator as they are, well, custom. You have to add them to the configuration manually. But still, the kickstarter can give you an idea of a valid configuration structure.

The config code you pasted above seems to be 1:1 from the docs. Of course this will not work because  it's just the docs, not the final configuration code. Please [read and try to understand the relevant sections of the docs](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids), it's all written there. Please also have a look at the [default genererator function](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/shape.js#L35) to learn how your custom generator has to look like.

Cheers, Joschi
