### ISSUE TITLE
SVG stack overflow

### ISSUE THREAD

**Issue by AgrawalAmey** [jkphl/svg-sprite#132]
I had been trying to use sprites to reduce the number of requests on a web page. My sprite consisted of SVGs of different sizes, using stack is gives white spaces due to the square view-box of parent SVG
[stack.zip](https://github.com/jkphl/svg-sprite/files/71656/stack.zip)

**Comment by jkphl** [comment]
Hey @AgrawalAmey,

so what exactly is the issue you'd like to file? All I see is expected behaviour ... As far as I understood SVG stacks, it's recommended that all shapes have the same size, so they are particularly useful for icon systems (if at all). 

In any case, if you think you've spotted erroneous behaviour, please describe in detail what you'd expect and post your complete configuration.

Thanks & cheers, Joschi

**Comment by AgrawalAmey** [comment]
Hi @jkphl,
Thanks for your response. I had been experimenting with says to substitute the symbol sprite so that the good old img element could be used. I tried running the process to create a stack for graphics of an  entire website, obviously the size of images are different. Running on default configuration with example set to true (Check out the attachment) I realized that though the view-box for every child SVG element 
is defined independently, as the parent SVG element has a square defined only square images are rendered perfectly. Others receive unexpected white space. This might not be refereed to as a bug for the module. But any suggestion in order to fix this problem will be really helpful.

Thanks, Amey
[svg-sprite.zip](https://github.com/jkphl/svg-sprite/files/71705/svg-sprite.zip)

**Comment by jkphl** [comment]
@AgrawalAmey In your case (and probably any similar one) I'd definitely recommend using the *symbol* sprite instead of stacks. Use it just as you'd do with a stack (`<img>` without `width` and `height` attributes and with fragment identifiers, e.g. `#10`) and throw in a [polyfill for older Internet Explorers](https://github.com/jonathantneal/svg4everybody) if necessary. That should just work out of the box in most of the browsers. IMO there's almost no real use case for stacks.

**Comment by AgrawalAmey** [comment]
@jkphl , Thanks for your suggestion. I had been just trying to explore options to substitute the use of `<use>` tag.

**Comment by jkphl** [comment]
@AgrawalAmey Ah, sorry, I just realize that my suggestion was wrong: I wanted to recommend the **view** sprite, not the *symbol* sprite.
