### ISSUE TITLE
How do you use the --svg-rootattrs?

### ISSUE THREAD

**Issue by chrisopedia** [jkphl/svg-sprite#144]
Attempting to do an svg sprite and it won't work doing it inline without the `xmlns:xlink="http://www.w3.org/1999/xlink"` on the root SVG.  So I tried adding in a via the CLI as such and its garbling the output.

```
svg-sprite --log --defs --defs-inline --defs-example \
--defs-prefix=icon- \
--defs-dest=./ \
--defs-sprite=symbol-defs.svg \
--shape-id-generator="icon-%s" \
--svg-rootattrs="attrs.json" *.svg
```

**Comment by jkphl** [comment]
hey @chrisopedia,

could you please post the exact contents of your `attrs.json` well as the garbled part of the SVG output?

Furthermore, AFAIK, when used inline there should be no need for explicitely having the `xlink` namespace declared. I don't find a proper normative reference right now, but e.g. [this article](http://taye.me/blog/svg/a-guide-to-svg-use-elements/) says the same (and I'm pretty sure it's correct).

**Comment by jkphl** [comment]
@chrisopedia Any updates on this? As I'm still pretty sure that no `xlink` namespace declaration is required for inline SVG, I'll close the issue at this point. Please feel free to reactivate in case of further problems.

**Comment by ghing** [comment]
I'm running into this issue as well (with regards to the `--svg-rootattrs` not being handled).

Here's my CLI invocation: 

    svg-sprite --dest img --symbol --symbol-dest \"\" --symbol-sprite sprite.svg --svg-rootattrs img/src/attrs.json img/src/noun_436905_cc.svg img/src/noun_96666_cc.svg

Here's my attrs.json:

    {
      "id": "svg-sprite"        
    }

And here's the SVG output (`img/sprite.svg`):

    <?xml version="1.0" encoding="utf-8"?><svg 0="i" 1="m" 2="g" 3="/" 4="s" 5="r" 6="c" 7="/" 8="a" 9="t" 10="t" 11="r" 12="s" 13="." 14="j" 15="s" 16="o" 17="n" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">...</svg>

That is, rather than being interpretted as a file path, each character of the option value is being added as an attribute to the inline `svg` element.

I looked through the CLI code and couldn't seem to find where the value of `--svg-rootattributes` was being parsed as a JSON file.
