### ISSUE TITLE
Matching sub-folders for source and destination

### ISSUE THREAD

**Issue by rgb4u** [jkphl/svg-sprite#170]
I can't force this plugin to use {base: './my/path/'} in gulp.src,
so i can keep folder structure in destination folder.
I want to compile svg files from folder:
project/src/a|b|c|d(...)/icons/*.svg
to folder:
project/dest/a|b|c|d(...)/icons/sprite.svg

Why i can't keep my file structure in destination folder while generating sprites?

**Comment by jkphl** [comment]
@rgb4u I'm sorry but I can hardly understand your question. If possible please try to rephrase it. Also, reading the [docs about output destinations](https://github.com/jkphl/svg-sprite/blob/master/README.md#output-destinations) might help you understand how *svg-sprite* has to be configured.

**Comment by rgb4u** [comment]
Sorry for my mistake, i try to set base, cwd for gulp.src without result
Every code compilation works fine, and my files matching 
source/destination folders,
only images don't work, sprites are generated, but not in 
.project/destination/**/
subfolders :(

**Comment by yoanmalie** [comment]
Hi
Can you re open this issue ? I have the same problem ! Can't keep the original folder structure even if i type the `base` option.

```
gulp.src('assets/img/sprite/**/*.svg', {base: '.'}) 
```

**Comment by jkphl** [comment]
Please understand that this is not an "issue" but intended behaviour. *svg-sprite* is for generating sprites, not for batch-optimizing SVG files. Please use SVGO for that. In order to create a sprite, the file paths need to get translated into a unique ID for each shape. The original file path is then irrelevant for *svg-sprite* and discarded. The fact that *svg-sprite* provides an option to keep and output the intermediate SVG files (with the IDs a file names) is nothing else than a convenience function.  As I said, please use SVGO directly for what you want to achieve.
