### ISSUE TITLE
Stripping parts of filenames

### ISSUE THREAD

**Issue by niksy** [jkphl/svg-sprite#176]
Is there a reason filename are stripped of some content here: https://github.com/jkphl/svg-sprite/blob/bb19260cda26e63f06db3adc5b0122f1b3b9f02f/lib/svg-sprite/shape.js#L141

When passing full file path to template, you get something along the lines `sers/foo/Projects/svg-sprite-test/assets/weather-clear-night.svg`, where `sers` part should be `/Users`.

Is there another way you can get full file path inside template, and if not, can the `shape.id.generator` callback be changed to have additional argument which is full file path?

**Comment by jkphl** [comment]
@niksy The `.name` property is intended to be the relative path of the source SVG inside the base directory where you are globbing / collecting your source files. That's the reason why `this.source.base` (= base directory) and one trailing path separator are stripped of the beginning of each file path.

In most situations you will have a directory, say `/Users/foo/Projects/svg-sprite-test/assets`, where all your source SVGs are stored, and you will want the file names to become the CSS class names. Sometimes you might even have sub directories that you will want to become part of the class name. In both cases you should glob and add your files e.g. like this:

```js
require('glob').glob('**/*.svg', {cwd: '/Users/foo/Projects/svg-sprite-test/assets'}, function(err, files) {
	files.forEach(function(file){

		// The vinyl way
//		var f = new File({
//			base: cwd,
//			path: path.resolve(path.join(cwd, file)),
//			contents: fs.readFileSync(path.join(cwd, file))
//		});
//		spriter.add(f);

		// The manual way
		spriter.add(
			path.resolve(path.join(cwd, file)),
			file,
			fs.readFileSync(path.join(cwd, file), {encoding: 'utf-8'})
		);
	});
}
```

If you do it like this and the `.name` property is still crippled, then please check whether you you have e.g. symlinks or special characters being part of the file name (so that the length might be skewed). Just a guess ...

Please let me know if this helps. Cheers, Joschi

**Comment by niksy** [comment]
Hm, this doesn’t fully solve the problem. I’m looking into having full path to file inside template data since I’m using custom template to generate output. Automatic class name generate is really nice in most cases, but for advanced functionality it would be nice to have access to full file object data.

**Comment by jkphl** [comment]
I get that. However, as the base path is constant, it should be easy to pass in a custom ID generator function (which you'd need in any case) that prepends the relative path with the constant prefix (or do with it whatever you like). I don't see the need to provide the full path as argument as you'd always be able to reconstitute it at any time, right? Also, you could always instantiate full File objects of the (prefixed relative) paths in case you need them. I think the input for the generator method should be as stupid and simple as possible. The method itself should be used for advanced processing.

**Comment by jkphl** [comment]
Also, I'm not convinced that the **ID generator method** is the correct place to introduce additional templating variables. You might look into custom templating functions instead and use the shape ID to reconstitute file properties.

**Comment by niksy** [comment]
What if I have list of SVG files which are (for some reason) placed in completely different folders and their base path differs?

**Comment by jkphl** [comment]
*svg-sprite* itself doesn't really care where your files are stored. Have a look at the example I gave above. The `spriter.add()` method expects 3 arguments:
1. The absolute file path
2. The relative file path within the base directory
3. The file content
The base directory is calculated from 1. and 2. You could try to hijack them and pass in the absolute path for both. It might work for you — cannot test it right now as I'm on my mobile phone only at the moment.

**Comment by niksy** [comment]
The thing is, I’m passing absolute path for both arguments and then I get the stripping issue :/

**Comment by jkphl** [comment]
Please provide your complete spriter configuration, the file and directory structure of your SVG shapes and the main script you're using to register your SVG files with the spriter. I'll see what I can find out.

**Comment by iambumblehead** [comment]
@niksy I had a similar issue to yours which I reported here (and accidentally closed) https://github.com/jkphl/svg-sprite/issues/178

The solution for me was to do this,
```javascript
filearr.map(f => path.resolve(f)).map(f => {
  spriter.add(f, path.basename(f), fs.readFileSync(f, 'utf-8'));
});
```

**Comment by niksy** [comment]
@jkphl here is the [Gist](https://gist.github.com/niksy/1a3ac61b00533d4bf9ddb02d3a930109) which you can clone and test. As you can see, foo.json contains invalid paths.

**Comment by niksy** [comment]
@jkphl Any progress on this?

**Comment by jkphl** [comment]
@niksy This was a tricky one, but I think you will like the solution:

Passing in an absolute path for the second argument when adding a file to the spriter queue is definitely not allowed. The reason is that *svg-sprite* uses vinyl files internally and some of that library's methods simply fail when no proper base directory is given (which is the case when you pass in two absolute paths). So, please pass your files in a proper format, e.g. like

```js
spriter.add(path.resolve('a.svg'), 'a.svg', fs.readFileSync(path.resolve('a.svg'), {encoding: 'utf-8'}));
```

To get the absolute file path into your template the `generator` callback now receives the complete vinyl file object as second argument, so you can do e.g. this to return the absolute file path:

```js
var config = {
	shape: {
		id: {
			generator: function (name, file) {
				return file.path;
			}
		}
	}
}
```

I hope this helps. Let me know!

**Comment by niksy** [comment]
@jkphl Yup, this is now working perfectly, thanks!
