### ISSUE TITLE
Markdown readability

### ISSUE THREAD

**Issue by toastal** [jkphl/svg-sprite#223]
The spacing on these docs in these Markdown files make this project almost unreadable. I think you're trying to use tabs for alignment, when browsers often show them as 8 characters. And if you're using tabs for indentation, usually people use spaces for alignment. Regardless, set these documents to 2 or 4 spaces so people can read it online please.

![What is this alignment, and how do I fix it](https://cloud.githubusercontent.com/assets/561087/24377697/75071732-12fd-11e7-8773-0cb23ecc8e64.png)

**Comment by alexrussell** [comment]
I guess it's just a style choice but I have to agree with OP - the choice to align all the values of the config is actually really annoying (and error-prone!) to read.

And I mean that completely aside from the fact that sometimes the values aren't correctly aligned due to the presumably different tab widths (which is just an extra reason that this is not good to use).

**Comment by jkphl** [comment]
Should be fixed as of 34d8c978e273fe98aedea22a1947f3fc24fe0aa5
