### ISSUE TITLE
Latest version of SVGO 1.1.0 breaks svg-sprite

### ISSUE THREAD

**Issue by longzheng** [jkphl/svg-sprite#276]
`svgo` just released [1.1.0](https://github.com/svg/svgo/releases/tag/v1.1.0) on npm which seems to break `svg-sprite`.

It seems to have broken a lot of other third-party tools as well, I believe this is related https://github.com/svg/svgo/issues/1030

```C:\Users\longz\Desktop\test>svg-sprite *.svg
(node:9800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'distribute' of undefined
    at SVGSpriterQueue.remove (C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\lib\svg-sprite\queue.js:97:58)
    at C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\node_modules\async\dist\async.js:473:16
    at next (C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\node_modules\async\dist\async.js:5329:29)
    at C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\node_modules\async\dist\async.js:969:16
    at C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\lib\svg-sprite.js:200:9
    at C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\node_modules\async\dist\async.js:473:16
    at next (C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\node_modules\async\dist\async.js:5329:29)
    at C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\node_modules\async\dist\async.js:969:16
    at C:\Users\longz\AppData\Roaming\npm\node_modules\svg-sprite\lib\svg-sprite\transform\svgo.js:92:3
    at <anonymous>
(node:9800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by jonnitto** [comment]
It is fixed with this version: https://github.com/svg/svgo/releases/tag/v1.1.1 svg-sprite should raise the dependency to ^1.1.1

**Comment by jkphl** [comment]
@jonnitto Awesome, thank you! Will do as soon as I find some minutes.

**Comment by AKrishma** [comment]
Please update if https://github.com/svg/svgo/releases/tag/v1.1.1 tag has been updated in package.json of svg-sprite of 1.4.0 tag. Since we are using gulp-svg-sprite 1.4.0 and which in turn using svg-sprite 1.4.0. This is causing lot of build breaks in multiple projects. So, early response from you will be highly appreciated.

**Comment by longzheng** [comment]
@AKrishma I think you should be able to fix your local by clearing your `node_modules` so it downloads fresh packages (it should grab the latest `svgo` now which has the fix)

**Comment by AKrishma** [comment]
@longzheng, provided worked for us.
Thankyou all for quick workaround.

**Comment by longzheng** [comment]
@jkphl If you want to brute force it, maybe just force install the latest version of `svgo` with `npm i svgo@latest`?

**Comment by jkphl** [comment]
@longzheng Will try (although SVGO already seems to be successfully updated to 1.1.1). Also, seems that some other dependencies require higher node versions in the meantime, so this might even end up in a version 1.5 for `svg-sprite` ... I'm on it.

**Comment by longzheng** [comment]
Sorry my bad, I misread your message.

**Comment by longzheng** [comment]
Just putting it out there, maybe another of the dependencies you updated is causing a different issue now? Have you tried just doing one build where you only update `svgo`?

**Comment by jkphl** [comment]
@longzheng Yeah, tried that, but there's no difference. The error messages are still about the same `UnhandledPromiseRejectionWarning` (builds for all node versions are failing, see https://travis-ci.org/jkphl/svg-sprite, although the tests vor Node 4 and 5 are failing for different reasons). So SVGO probably isn't the true / only reason. I'll be having a meeting in 15 minutes, but I'll try to fix this as soon as possible. If you've got any further ideas I'd highly appreciate them in order to speed things up.

**Comment by longzheng** [comment]
Ok, I'm a node noob but I figured out the actual cause of the exception was not `svgo`.

I checked out your commit `b9a2df3702d6f7322d6f0bc3df2edcdab88a9a14`

When running the tests, this line https://github.com/jkphl/svg-sprite/blob/b9a2df3702d6f7322d6f0bc3df2edcdab88a9a14/lib/svg-sprite/transform/svgo.js#L83

was causing an exception 
```
TypeError: Cannot read property 'level' of undefined
    at C:\Users\longz\Desktop\test\jkphl\svg-sprite\lib\svg-sprite\transform\svgo.js:83:45
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)"
```

Inspecting `spriter.config.log.transports` it looks like this is not an object but an array.
![screen shot 2018-09-18 at 6 16 07 pm 2](https://user-images.githubusercontent.com/484912/45673825-12719e00-bb6f-11e8-9827-c147b05bc9f1.png)

I have no context of what this is or why it has been changed (another dependency breaks it?) but that's the actual error.

If i change to `spriter.config.log.transports[0].level` it all works, but I'm not sure that's the intended behaviour.

**Comment by longzheng** [comment]
Set up a demo https://github.com/jkphl/svg-sprite/pull/277

The tests still fail, but it's failing on sprites not matching.

**Comment by jkphl** [comment]
@longzheng Awesome, thanks for the pointer! This must be it! I'm just back from my meeting and will look at it asap. Looks like this is something related to *winston* (the logger used by *svg-sprite*). Btw, errors because of non-matching sprites are usually harmless and the result of minor (= sub-pixel) rendering changes in image comparing libraries.

**Comment by jkphl** [comment]
I just pushed out the release `1.4.1` with only minimal dependency updates which should fix the SVGO issue. Gulp & Grunt versions will follow shortly. It turned out that updating all dependencies caused a separate problem (which looked very similar though) — I'll do that along with a `1.5.0` release (as I'll have to drop support for Node.js < 6.4 then as well). Thanks for all your help!
