### ISSUE TITLE
Padding shouldn't be the part of icon

### ISSUE THREAD

**Issue by shafqatali** [jkphl/svg-sprite#281]
Hi Joschi Kuphal

I am not reporting an issue, Actually, its  a suggestion, When we generate SVG sprite using this config

```
config = {
        shape: {
            spacing: {         // Add padding
                padding: 15
            },
        },
        mode: {
            css: {     // Activate the «css» mode
                render: {
                    css: true  // Activate CSS output (with default options)
                }
            }
        }
    };
```

It adds the padding to icon's dimension, i.e suppose an icon size is 16x16 pixel, using the above configration  in the output css icon size will be 36x36px.

I think it's not correct the gap should be outside the icon and the icon should remain 16x16px.

I hope you will update this in the next version.

Regards

**Comment by jkphl** [comment]
@shafqatali Thanks for your suggestion. However, I don't see the point in this — actually you shouldn't use `padding` in that case at all. For an icon sprite to work properly, you'd have to have an HTML element that fits exactly the icon dimensions (otherwise, neighbouring icons would "bleed" into the displaying area). That said, if you'd want to have padding around the icon in your layout, you'd have to apply the padding to the *embedding HTML element* (not to the icon shape), and that's beyond *svg-sprite*'s scope by definition (should be part of your page CSS). The `padding` option only makes sense for the (rare) occasions when you'd want to have padding as part of the icon shape itself (thus adding to the icon dimensions). Not sure if I managed to express myself clearly ...
