### ISSUE TITLE
unversioned dependency problem on locked dependencies project

### ISSUE THREAD

**Issue by atilafassina** [jkphl/svg-sprite#44]
Hello!

I might a problem using svg-sprite with **grunt-svg-sprite** when locking dependencies with **npm shrinkwrap**

on `package.json`, [line 38](https://github.com/jkphl/svg-sprite/blob/master/package.json#L38) there's defined lodash as a dependency without version

```
"lodash": "lodash/lodash",
```

On `grunt-svg-sprite` dependencies, it generated with a `git+https` path, that would download any version, as far as I understand... possibly breaking the plugin if any major changes happen.
```
 "lodash": "git+https://github.com/lodash/lodash",
```

And, after locking dependencies with shrinkwrap it generates a relative path that's not working when I'm testing on different environments.

```
"from": "../../../../../../../var/folders/9f/39z7bx0s7sjgx9bqf1yqdjmh0000gn/T/npm-36893-3e27cd04/1421851729890-0.2797100490424782/ef3f0a0bb9f032d2eb3559fe9bcb5f49668c6f5f",
```

Does this all makes sense to you?
If so, I imagine the simplest solution would be to determine a version for lodash here, right?

**Comment by jkphl** [comment]
Hi @atilafassina,

thanks for your report. First of all, I have to say that I have no clue of shrinkwrap at all and I didn't test it during development.

Furthermore, when I was writing *svg-sprite* at around christmas, *lodash* was available in version 2.41, but I was relying on functionality that would be introduced with the upcoming v3.0, so I had to use the unversioned dependency to enforce the use of the latest sources from GitHub.

I just realized that the v3.0 of *lodash* is [available since monday](https://github.com/lodash/lodash/releases), so I'll happily go and update my dependency as soon as possible. I'll push out another release probably tonight or tomorrow.

Cheers,
Joschi

**Comment by atilafassina** [comment]
wow! Thanks a lot, @jkphl 
That's probably gonna do the trick!!

After your commit, I'll test again and post the feedback here...

**Comment by jkphl** [comment]
You're welcome. Well, it looks like there's no official v3.0 NPM package yet. Will need to wait for that one. Stay tuned. ;)

**Comment by atilafassina** [comment]
:+1:  ok!
I'll keep an eye on that as well.

**Comment by jkphl** [comment]
Seems we'll have to wait until next Monday: https://twitter.com/jdalton/status/558308326862098432

**Comment by atilafassina** [comment]
Yeah... took some while more,
but it's [released](https://www.npmjs.com/package/lodash) =)

**Comment by jkphl** [comment]
Thanks for the heads up. Will try to push out another release tonight! :)

**Comment by atilafassina** [comment]
:+1: thanks a lot!

**Comment by jkphl** [comment]
The [new release](https://github.com/jkphl/svg-sprite/releases/tag/v1.0.12) is out — hope this works for you now! :)

**Comment by atilafassina** [comment]
It did the trick! :tada: 
Thanks a lot @jkphl

**Comment by jkphl** [comment]
You're welcome! Thanks for the feedback. :)
