### ISSUE TITLE
How set empty prefix?

### ISSUE THREAD

**Issue by phpprog** [jkphl/svg-sprite#47]
Hello! 

I generate full selectors in function and don't want use prefix. But I can't set empty prefix (it always equal '.') and I do this:

```
config: {
...
prefix: ''
...
}

generator: function(name) {
    var selector = doSmthng(name); // selector === '.selector .icon' 
    return selector.substr(1); // return 'selector .icon'
}
```

and then I have '.selector .icon' in css.

I do not like this crutch: `selector.substr(1)`.  How do I get rid of it?

**Comment by jkphl** [comment]
What you are doing is not the way the ID generator function is to be used! It should generate a unique **ID**, not a CSS selector! An ID **must not contain whitespace, special characters** etc. As the ID will be used as `id` attribute in the SVG, this will break validity. Please use the options as intended.

**Comment by phpprog** [comment]
Oops! ) 
But it seemed to me this is a simple solution generate complex selectors, like `.a .b.c .d::after`,  which stored in the array in finished form. Maybe advise something else? :)))

**Comment by jkphl** [comment]
Well, this is exactly what the `prefix` option is for. You just need to insert something like `.a .b.c .%s::after` (the placeholder `%s` will get replaced by the individual shape IDs). Also, you may always use a custom rendering template to create your very own stylesheet variant.

**Comment by phpprog** [comment]
Unfortunately in my case changing the entire string, not only '.d', so  individual shape ID must be inserted instead of a `.a .b.c .d::after`.

I'll try anything to do with it. Thank you.

**Comment by jkphl** [comment]
In this case, you'll probably not succeed without writing your own template respectively extending a standard one. Are you using a CSS preprocessor? I'm mostly familiar with Sass, so I'll use that for the following explanation:

* Let *svg-sprite* render the Sass template with a custom file name so that it starts with an underscore (e.g. `_sprite.sass`)
* Create a custom Sass file (e.g. `sprite.scss`) and `@import` the created file.
* Write a CSS rule with your desired selector (e.g. `.a .b.c .d::after`) and `@extend` the default rule created by *svg-sprite* for a specific shape ID

You should end up with two identical CSS rules, one with the original (ID based) selector and another one with your custom selector.
