### ISSUE TITLE
Specify different paths for generated sprite and css

### ISSUE THREAD

**Issue by justineberger** [jkphl/svg-sprite#59]
Hey again Joschi

Is it possible to have control over the path for where the css is stored, and another for the sprite ?
right now the sprites are stored inside the css folder. I would prefer to keep them outside. I can move the folder of course but then the paths in the css won't work...

Thanks

**Comment by jkphl** [comment]
Hey @justineberger,

that's totally possible. Please have a look [here](https://github.com/jkphl/gulp-svg-sprite/issues/12#issuecomment-72636077) for an explanation of the several path options (replace `<yourmode>` with `css` or `view` respectively):

* Basically, there's a general output directory for your sprite mode (constructed of `dest` + `mode.<yourmode>.dest`) (see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#main-output-directory)).
* The sprite will be put at `<main-output-dir>` + `mode.<yourmode>.sprite` (see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties) for details).
* The CSS resources will be put at `<main-output-dir>` + `mode.<yourmode>.render.css.dest`

All of these paths may be specified absolutely. If they aren't, they are interpreted relatively as shown above.

Does this answer your question / solve your problem?

Cheers,
Joschi

**Comment by justineberger** [comment]
Yes, thank you, it seems to work okay. I know the answers to my questions are probably somewhere in the doc, but it's really difficult to find and get a grasp of it. I'm starting to fall asleep on my pc so i'll play around a bit more tomorrow (i've been grunting non-stop for 10 hours, this stuff is awesome, but soo time consuming, haha). But, awesome support man !

**Comment by jkphl** [comment]
Glad that it works out for you, and happy to help. You're welcome! :)

**Comment by jkphl** [comment]
Oh, and yes, I know that there are really a lot of options and that it's hard to understand all that (imagine what's going on in my brain when writing all this code and docs!). I'm trying hard to constantly improve the docs and everything ... Cheers!

**Comment by Eworm** [comment]
Hi,

I'm also trying to set different folders for the sprite and scss file, but I'm having a hard time getting the path to the sprite right in the scss file. It's ok to have the sprite & scss file in img/sprite, but I can't get the path to the svg right no matter what I do. Could you maybe take a look at my setup?
```
svg_sprite: {
            complex: {
                // Target basics 
                expand: true,
                cwd: 'img-src/sprite',
                src: ['**/*.svg'],
                dest: 'img/sprite',

                // Target options 
                options: {
                    mode: {
                        view: {
                            dest: '',
                            sprite: 'img/sprite.svg',
                            bust: false,
                            render: {
                                scss : true,
                            }
                        },
                        symbol : false
                    }
                }
            }
        }
```

**Comment by jkphl** [comment]
Hey @Eworm,

could you please tell me what you considered the "right" path to the sprite in your Sass file?

I tried your example and it works just as expected:

* Your main ouput directory is `"img/sprite"` (relative to the directory where you run Grunt).
* You set `mode.view.dest` to an empty string, which is basically the same as `"."`, so the base directory for your «view» sprite and accompanying files is `"img/sprite"` as well. This is also the directory where your **final CSS is expected to be located**. (Remember, you're creating a «view» sprite, which is a CSS sprite that only works in conjunction with a CSS stylesheet).
* You set `mode.view.sprite` to `"img/sprite.svg"`, which is relative to your «view» base directory, resulting in a final sprite path of `"img/sprite/img/sprite.svg"`.
* Next, you decide to let *svg-sprite* render a Sass stylesheet instead of plain CSS. You don't set a custom location for it, so it'll be dropped at `"img/sprite/sprite.scss"` (just where the final CSS file is expected). The path used inside the Sass stylesheet for referencing the sprite is `"img/sprite.svg"` — which is perfectly correct, given that the CSS compiled from the Sass file is located at `"img/sprite/sprite.css"` (which is just what you configured).
* It's up to you to ensure that your final CSS file will be placed at the right location, that's beyond the scope of *svg-sprite*.

I hope I could shed some light on this admittedly complex topic.

Cheers,
Joschi
