### ISSUE TITLE
Add style attribute to svg element

### ISSUE THREAD

**Issue by nguyenj** [jkphl/svg-sprite#63]
Thanks in advance for the help.

I just have question on how to add a style inline attribute to the svg element. Something along the lines of `style="display:none;"`?

**Comment by jkphl** [comment]
Hi @nguyenj,

at present there is no support for altering the sprite SVG, but I might consider adding a post-processing option in a future release.

On the other hand, I assume you are asking because you are using the «defs» or «symbol» sprite and want to inline it into an HTML document, right? Did you consider using the `mode.<mode>.inline` option ([documentation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#defs--symbol-mode)), which basically adds `width="0" height="0" style="position:absolute"` to hide the sprite in the document? (I can't remember the exact reason, but there were some objections to using `display:none` ...)

Cheers,
Joschi
