### ISSUE TITLE
Make it possible to use it at Media Query [SASS output, %extend svg-common -> @mixin svg-common]

### ISSUE THREAD

**Issue by PeterMK85** [jkphl/svg-sprite#66]
Due to the current limitation of SASS (You can't extend % or . classes in a media query, but you can with a mixin), is there a way to transform the genrated %svg-common into a @mixin ?

The "classes" I was able to alter it down to placeholder (or silent classes) or mixins but because the first property of them is:
@extend %svg-common;

It actually fails during the compile.

**Comment by jkphl** [comment]
Hi @PeterMK85,

thanks for requesting this feature. In fact, I was reading about this myself a couple of days ago, and I'd also be interested in extending the classes from within media queries. Unfortunately, my time is extremely limited these days ... Would you be able to provide a complete example of how the Sass output (including the mixin) would have to look like? That'd speed it up a lot ...

Thanks & cheers,
Joschi

**Comment by jkphl** [comment]
Ah ok, looks easy. So wouldn't it be sufficient to provide a boolean "mixin" option that toggles between the @mixin and the @extend style?

**Comment by PeterMK85** [comment]
Yep that would be great to choose by a parameter :+1:

**Comment by jkphl** [comment]
Continued [here](https://github.com/jkphl/grunt-svg-sprite/issues/41).

**Comment by falcik** [comment]
I'm currently working with a project and I have generated my icons in SCSS with classes instead of mixins. Now I figured out that some of the icons need to be changed within the media queries. Author has provided an option that toggles between @mixin and @extend styles. I wonder if it is possible to have them both? For example all icons use @extend style, but icons with name (as example "my-icon~mixin.svg")  would have mixin generated instead of classname?
