### ISSUE TITLE
Unwanted grouping of elements

### ISSUE THREAD

**Issue by baardbaard** [jkphl/svg-sprite#85]
I have two svg's that look perfectly fine, but the sprite file that svg-sprite creates does some weird grouping of elements and I don't know why. You can download the SVG files here: https://dl.dropboxusercontent.com/u/1409173/svg-sprite-baardbaard.zip

Before svg-sprite:
![before](https://cloud.githubusercontent.com/assets/881521/7654808/08474136-fb20-11e4-80bc-3af3a949f2fd.png)

After svg-sprite:
![after](https://cloud.githubusercontent.com/assets/881521/7654809/0849d784-fb20-11e4-88dc-1a0306174d6c.png)

This is my gulpfile:
```
gulp.task('svg', function() {
   gulp.src(paths.svg)
   .pipe(svgSprite({
     mode: {
       css: { // Activate the «css» mode
         bust: false,
         render: {
           css: true // Activate CSS output (with default options)
         },
         example: true
       }
     }
   }))
   .pipe(gulp.dest('_/out'));
});
```

Thank you!

**Comment by jkphl** [comment]
Hi @baardbaard,

I'm pretty sure this is not an *svg-sprite* problem but caused by SVGO instead. Some of the SVGO plugins are known for being too "aggressive" with some SVG files. Please try deactivating the plugins as [shown here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#pre-defined-transformation-with-custom-configuration-object-values). You may make your live easier by using the [svg-sprite configuration kickstarter](http://jkphl.github.io/svg-sprite) for that (section "SVG shape transformations").

Please let me know if this works for your!

Cheers,
Joschi

**Comment by baardbaard** [comment]
Thanks Joschi, it was indeed an SVGO plugin setting. Once I set mergePaths to false everything looked alright.

**Comment by jkphl** [comment]
Glad it worked out! Happy spriting! :)
