### ISSUE TITLE
Stylus output by this template

### ISSUE THREAD

**Issue by werty1001** [jkphl/svg-sprite#86]
Hi, is it possible to generate stylus file for this template:

**$icon_name = offset_x offset_y width height icon_name;**
**$svg_common = width height image_path;**

For example content in svg-sprite.styl:
```
$search = 0px 0px 72px 72px 'search.svg';
$home = 0px -72px 22px 22px 'home.svg';
$prev = 0px -94px 12px 12px 'prev.svg';
$svg_common = 206px 72px 'sprite.svg';
```

**Comment by jkphl** [comment]
Hi @werty1001,

I'm sorry but I don't understand one single word of your request. :( This might be the case because I'm not a Stylus user ... Please tell me what you need this for. Also, have you already considered [customizing the default Stylus template](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) to suit your needs? Doesn't that work in your case?

Cheers,
Joschi

**Comment by werty1001** [comment]
I created my template **stylus.svgsprite.handlebars**:

```
/*

$icon = width height offset_x offset_y;
$spritesheet = width height image;

*/
{{#shapes}}
${{name}} = {{width.outer}}px {{height.outer}}px {{position.absolute.x}}px {{position.absolute.y}}px;
{{/shapes}}
$spritesheet = {{spriteWidth}}px {{spriteHeight}}px 'sprite.svg';
```

And add this in gulp task
```
	render:
		styl:
			template: './src/mustache/stylus.svgsprite.handlebars',
			dest: './src/stylus/sprite-svg.styl'
```

It work : ) 
```
/*

$icon = width height offset_x offset_y;
$spritesheet = width height image;

*/
$gape = 74px 74px 0px 0px;
$search = 74px 74px -74px 0px;
$weather-clear = 52px 52px 0px -74px;
$weather-clear-night = 52px 52px -52px -74px;
$weather-few-clouds = 52px 52px -148px 0px;
$spritesheet = 200px 126px 'sprite.svg';
```

**Thanks for the reply and for the great plugin!**
