### ISSUE TITLE
Adding custom attributes to `rootAttributes`

### ISSUE THREAD

**Issue by iMoses** [jkphl/svg-sprite#87]
Is it possible? Unless I missed something it doesn't seem to be extendable.
I think it's an important and easy enough feature/option to add.

If there's a way I'd like to hear about it and if not then consider this as a feature request.

**Comment by jkphl** [comment]
Hi @iMoses,

thanks for the suggestion. In general I agree, although I think it shouldn't be *svg-sprite*'s job to do these kind of SVG modifications. For a lot of users the available configuration options are already overwhelming enough. ;)

However, I already considered [adding a global post-transformation on the final sprite](https://github.com/jkphl/svg-sprite/issues/64), which would totally suit your need. Due to my current workload this will take me some time to implement though. Thanks for your patience.

Cheers,
Joschi

**Comment by iMoses** [comment]
Are you expecting code contributions?
This library is the only one who suits my needs other than this little issue.
I really need to add to the root element the `preserveAspectRatio="none"` attribute.
I have no problem implementing the option and I would prefer it would be a part of the official library and not some fork of mine.

**Comment by jkphl** [comment]
I fully agree that splitting of a fork just because of this one wouldn't make much sense. However, I also don't think *svg-sprite* should have extra options for each and every special case, so using a generic post-transformation for this (and other) modifications seems right to me. I'll put this high on my schedule, ok?

**Comment by iMoses** [comment]
Okay, thanks.

P.S. I agree, the best solution in this case should be generic, not specific.

**Comment by jkphl** [comment]
As of [release v1.2.0](https://github.com/jkphl/svg-sprite/releases/tag/v1.2.0) there are now two options to add custom root attributes:

1. You may use the new `svg.rootAttributes` option to do just that ;) (decided to introduce this as an easy shorthand for the next one)
2. Additionally you can now specify global post-processing transformation callbacks via `svg.transform` which get called with the full SVG source ...

I'm pretty sure you can now achieve what you wanted to, right?

Cheers,
Joschi
