### ISSUE TITLE
Selectors template

### ISSUE THREAD

**Issue by yoyurec** [jkphl/svg-sprite#91]
How to delete **:regular** pseudoclass using templates?

**Comment by jkphl** [comment]
Hey @yoyurec,

that might be a tricky one, but it should be possible. [In the Mustache template](https://github.com/jkphl/svg-sprite/blob/master/tmpl/css/sprite.css#L5), instead of running through and printing all the generated CSS selectors

```css
{{/hasCommon}}{{#shapes}}{{#selector.shape}}{{expression}}{{^last}},
{{/last}}{{/selector.shape}} {
	...
}
```

you might explicitly just pick the first one (the `:regular` selector is always second, if at all):

```css
{{/hasCommon}}{{#shapes}}{{#selector.shape.0}}{{expression}}{{/selector.shape.0}} {
	...
}
```

That's off the top of my head, I didn't test it. Please let me know if this works for you.

Cheers,
Joschi

**Comment by yoyurec** [comment]
Works perfect! Tnx
